### ISSUE TITLE
Create a VS code extension

### ISSUE THREAD

**Issue by mungojam** [ukoloff/win-ca#1]
This would be really handy for us as we can't currently use the GitHub extension in VS code because of our internal SSL certificate. 

It's a bit beyond my node skills at present. And I can't be certain that it's possible for a VS code extension to do this. 

It was suggested in https://github.com/Microsoft/vscode-github-issues-prs/issues/28#issuecomment-388318961

**Comment by ukoloff** [comment]
If someone is still interested, VSCode Extension `win-ca` is created, that does nothing but imports `win-ca` package to load Windows' Trusted Root Certificates into `https.globalAgent.options.ca`. Other extensions should see them.

**Comment by mungojam** [comment]
It would be cool if you can publish the version that you made for me that worked. 

Can I make an odd request that you version it >= 1.0.4? I can't figure out how to stop VS using a cached extension so I already had to change your last one to 1.0.3 manually (because of the previous test 1.0.2 version)

**Comment by ukoloff** [comment]
Yes, new version will be at least v1.1.0.

But Node.js package `win-ca` should be updated first. After that new version of VSCode extension is piece of cake.

**Comment by ukoloff** [comment]
New version of Node package & VSCode extension released - v2.1.0.

Please, give it a try.

**Comment by mungojam** [comment]
Works perfectly thanks.

Had a nosey and now there are lots of .0 files and the .pem file. I guess each one is a separate root certificate and that is how you've designed it to work.
