### ISSUE TITLE
How can i solve this problem?Thanks

### ISSUE THREAD

**Issue by ZhangJian01** [ukoloff/win-ca#10]
First of all,thanks for making such amazing tool.But when i have installed win-ca,my project couldn't run successfully.Could you please tell me what with it?Thanks very much!
    ./node_modules/win-ca/lib/index.js 5:2
    Module parse failed: 'return' outside of function (5:2)
    You may need an appropriate loader to handle this file type.
    |
    | if (process.platform !== 'win32') {
    >   return;
    | }
    |

**Comment by ZhangJian01** [comment]
I just installed win-ca,and then required it in my electron app.I didn't do anything others.

**Comment by ukoloff** [comment]
Sorry, I have no expertise in Electron, can't say anything.

But Issue #8 deals with Electron 3.0. I think, its author could make `win-ca` work under Electron. May be you can talk with him?

**Comment by ZhangJian01** [comment]
All right,thank you very much.

**Comment by ukoloff** [comment]
See https://github.com/ukoloff/electron-win-ca for example of using `win-ca` under `Electron`.
