### ISSUE TITLE
npm install - node 10.6

### ISSUE THREAD

**Issue by lenisha** [ukoloff/win-ca#11]
Hi , can't install the module - what would be the way to troubleshoot the errors?
It's on
Windows 10.0.14393 
3020 verbose node v10.6.0
3021 verbose npm  v6.1.0
Are Admin permissions required?

```
012 silly saveTree `-- win-ca@2.3.0
3012 silly saveTree   +-- is-electron@2.2.0
3012 silly saveTree   +-- make-dir@1.3.0
3012 silly saveTree   | `-- pify@3.0.0
3012 silly saveTree   +-- node-forge@0.7.6
3012 silly saveTree   `-- split@1.0.1
3012 silly saveTree     `-- through@2.3.8
3013 warn demo-node@1.0.0 No description
3014 warn demo-node@1.0.0 No repository field.
3015 verbose stack Error: win-ca@2.3.0 postinstall: `node -e "try{require('.')}catch(e){}"`
3015 verbose stack Exit status 3221225477
3015 verbose stack     at EventEmitter.<anonymous> (D:\Program Files (x86)\npm\6.1.0\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
3015 verbose stack     at EventEmitter.emit (events.js:182:13)
3015 verbose stack     at ChildProcess.<anonymous> (D:\Program Files (x86)\npm\6.1.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
3015 verbose stack     at ChildProcess.emit (events.js:182:13)
3015 verbose stack     at maybeClose (internal/child_process.js:961:16)
3015 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
3016 verbose pkgid win-ca@2.3.0
3017 verbose cwd D:\home\site\wwwroot
3018 verbose Windows_NT 10.0.14393
3019 verbose argv "D:\\Program Files (x86)\\nodejs\\10.6.0\\node.exe" "D:\\Program Files (x86)\\npm\\6.1.0\\node_modules\\npm\\bin\\npm-cli.js" "install"
3020 verbose node v10.6.0
3021 verbose npm  v6.1.0
3022 error code ELIFECYCLE
3023 error errno 3221225477
3024 error win-ca@2.3.0 postinstall: `node -e "try{require('.')}catch(e){}"`
3024 error Exit status 3221225477
3025 error Failed at the win-ca@2.3.0 postinstall script.
3025 error This is probably not a problem with npm. There is likely additional logging output above.
3026 verbose exit [ 3221225477, true ]
```

**Comment by ukoloff** [comment]
1. As far as I know, admin privileges are not required
2. But you never know on Windows ;-)
3. `errno 3221225477` is likely to mean `Error while loading N-API module`
4. Can you try other with Node.js versions? v8, v10-latest?
5. After failed installation, does `node_modules/win-ca` folder remains (not deleted)?
6. If yes, issue one-liner:
```cmd
node -r win-ca/lib/binding
```
This will try to just load N-API module.

**Comment by ukoloff** [comment]
And also
```sh
node -p process.versions
```

**Comment by ukoloff** [comment]
For Node v8.9.4 I found a bug - win-ca@2.3.0 missed a file in binary package, fixed in win-ca@2.3.1 (just published).

For Node v10 I'm still puzzled. It should work and works for me. Run those two one-liners under Node v10.6.0

**Comment by lenisha** [comment]
tried on 10.6 the new version 2.3.1:

D:\home\site\wwwroot>node -p process.versions
{ http_parser: '2.8.0',
  node: '10.6.0',
  v8: '6.7.288.46-node.13',
  uv: '1.21.0',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.32.0',
  napi: '3',
  openssl: '1.1.0h',
  icu: '61.1',
  unicode: '10.0',
  cldr: '33.0',
  tz: '2018c' }

D:\home\site\wwwroot>node -r win-ca/lib/binding
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'win-ca/lib/binding'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at Module._preloadModules (internal/modules/cjs/loader.js:805:12)
    at preloadModules (internal/bootstrap/node.js:539:7)
    at startup (internal/bootstrap/node.js:238:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)

**Comment by ukoloff** [comment]
> but on the failure it does not leave win-ca module in filesystem, is there some tracing to enable more info on failure?

Well, in this case simple one-liner cannot help us.

You need force `win-ca` to remain on disk. Either download [tarball](https://ci.appveyor.com/api/buildjobs/wspq3qaunr1v0rhc/artifacts/win-ca-2.3.0.tgz) and extract manually or (better) try
```cmd
npm i --ignore-scripts win-ca
```
And when `node_modules\win-ca` exists, issue
```
node -r win-ca/lib/binding
```

**Comment by lenisha** [comment]
thank you for your help it worked perfectly well, once I switched platform architecture to use 64 bit processes. Some disconnect there between Windows 10 64 bit processes and node running space.
