### ISSUE TITLE
Initializing crypt32-{arch}.node fails in vscode extensions when run in vscode Insiders 1.31.0

### ISSUE THREAD

**Issue by StephenWeatherford** [ukoloff/win-ca#12]
See https://github.com/Microsoft/vscode-docker/issues/733.

I assume this is related https://github.com/ukoloff/win-ca/issues/8, but I don't fully understand the issues involved.  vscode runs in Electron, but extensions run in a separate process, so I assume Electron has no effect on them.  VS Code Insiders 1.31 has switched from Node 8.9.3 to 10.2.0, and process.versions.nApi is set to "3" there.  If I force each.fallback to load, I don't have any problems.

Any ideas on what's going on here?  Is it somehow a vscode issue?  Thanks!

process.versions on VS Code 1.30.2:
![image](https://user-images.githubusercontent.com/6913354/50868964-e751cb00-1366-11e9-8cd9-80bacd295246.png)

process.versions on VS Code Insiders 1.31.0:
![image](https://user-images.githubusercontent.com/6913354/50868974-f6d11400-1366-11e9-8cdd-9dd9c0221308.png)

**Comment by StephenWeatherford** [comment]
@bpasero This appears to be caused by the move to Electron 3 (https://github.com/Microsoft/vscode/issues/52629).  win-ca (see also https://github.com/Microsoft/vscode/issues/52880, cc @chrmarti) is trying to use load an N-API module(?), but this fails on Electron (https://github.com/Microsoft/vscode/issues/52880), so it uses a fallback if it detects it's running on Electron.  This detection returns false in a vscode extension, so the fallback isn't used and loading the module fails.

Does the vscode extension process run in an Electron context?  I had thought not, but not sure exactly what that means.

**Comment by ukoloff** [comment]
I also don't understand the details of interaction between Electron & VS Code. It looks like VS Code hides Electron. 

`is-electron` checks `window.process.renderer`, `process.versions.electron` and `navigator.userAgent`, but `window == navigator == undefined` and `process.versions` knows nothing about `electron`.

So, we should somehow detect we are running in VS Code Extension Host, but I have no idea how to do it.

**Comment by bpasero** [comment]
@StephenWeatherford the extension host process is running in a forked Electron process, that is a node.js environment but with the V8 version of Electron. 

Please note that we currently do not recommend to use native modules in extensions for this reason, you will have to update the extension for each Electron update we do. In the future we will investigate to support N-API to make this a bit easier for extension authors.

**Comment by bpasero** [comment]
@ukoloff may I ask why you need to know that you are running inside the extension host?

**Comment by ukoloff** [comment]
> @ukoloff may I ask why you need to know that you are running inside the extension host?

I only need a hint - is N-API available or should we fallback. 

I mean regular N-API. Electron uses its own N-API, I don't want to use it. If I could detect Electron, it would suffice.

**Comment by ukoloff** [comment]
As far as I know, Electron uses its own N-API, which is [incompatible](https://github.com/nodejs/node-addon-api/issues/269) with Node.js' one. 

I don't know, if `process.version` can be used to detect that difference. I suppose it cannot.

May be one could compare `process.version` against `process.versions.v8` and deduce whether Electron is used or not. But I have neither will nor time to support this. There must be npm package for this or some official API or whatever.

**Comment by bpasero** [comment]
@ukoloff I see. We have https://github.com/Microsoft/vscode/issues/62315 to support this but it is not yet in any version of VSCode.

**Comment by StephenWeatherford** [comment]
(FYI, If you look at the process versions I showed up, the detection of electron didn't change - it returned false before, too - the difference is that nApi started showing up in versions so win-ca stopped using the fallback.)

@ukoloff Is there a way I as a caller could force you to always use the non-nAPI fallback?  Thx.

**Comment by ukoloff** [comment]
> (FYI, If you look at the process versions I showed up, the detection of electron didn't change - it returned false before, too - the difference is that nApi started showing up in versions so win-ca stopped using the fallback.)
> 
Oh, that's interesting! 

> @ukoloff Is there a way I as a caller could force you to always use the non-nAPI fallback? Thx.

So far, there is no such possibility. Adding this configuration parameter is easy but not user friendly IMHO.  I'll try to figure another way to handle the problem.

**Comment by StephenWeatherford** [comment]
@ukoloff Thanks, really appreciate it!

**Comment by ukoloff** [comment]
`win-ca` v2.4.0 is published, both npm module and VS Code extension.

It works for me (both in regular VS Code and CS Code Insiders), but more testing is needed

**Comment by StephenWeatherford** [comment]
@ukoloff I really appreciate the quick turn-around, sorry for the delay in trying this out.  I'm still seeing the problem.  Here's what I see:

`nApi = !!process.versions.napi;` -> true

`nApi && (nApi = this === require('../fallback'));` -> true

`nApi && (nApi = !(this.electron = require('is-electron')()));` -> this.electron = false, nApi = true

`this.each = require((this.nApi = nApi) ? './each' : './each.fallback');` -> error loading DLL

**Comment by StephenWeatherford** [comment]
I get the same result if I run the extension in ./vscode and change `require('win-ca/fallback')` to `require('win-ca')`.

**Comment by ukoloff** [comment]
@StephenWeatherford The problem is here:
```
nApi && (nApi = this === require('../fallback')); -> true
```
For me it is `false`. Cannot imagine how it could be `true`.

The following files should be executed in that order:
1. `win-ca/fallback/index.js`
2. `win-ca/lib/index.js`

Is it true?

**Comment by StephenWeatherford** [comment]
I don't understand how this is supposed to work. fallback/index.js just requires "..", which is win-ca's root folder, which requires lib/index.js, which is the original file loaded, no?

**Comment by StephenWeatherford** [comment]
Your vscode extension uses `require('win-ca/fallback')` instead of `require('win-ca')`.  Am I supposed to be doing that?  I'm currently doing `require('win-ca')` as before.

**Comment by ukoloff** [comment]
> Your vscode extension uses `require('win-ca/fallback')` instead of `require('win-ca')`. Am I supposed to be doing that? I'm currently doing `require('win-ca')` as before.

Yes, if you call `win-ca` inside VSCode, you should `require('win-ca/fallback')`,
since there is no *portable* way for `win-ca` to know it runs inside VSCode.

By the way, I don't quite understand why you should require `win-ca` yourself. Do you develop your own VS Code extension?

The intended usage is just to install `win-ca` *extension*, it will call `win-ca` *module* which fetches list of root certificates and installs it to `https.globalAgent.options.ca` (available to all other installed *extensions*).

Of course, you can call `win-ca` yourself if you know what are you doing. Any way, you should make it use fallback, as stated before.

**Comment by StephenWeatherford** [comment]
Thanks, that does fix it, I just thought it was supposed to auto-detect.

> The intended usage is just to install win-ca extension, it will call win-ca module which fetches list of root certificates and installs it to https.globalAgent.options.ca (available to all other installed extensions).

Been wanting to talk to you about that.  I don't like the idea that installing an extension will affect other extensions' behavior (unless you're doing it on purpose by installing your vscode extension as a user). In fact, I take pains to pull out the values and have them not affect the global state.

Imagine that you're an extension author and that some users claim certificates work and some claim they don't, and what you don't know is that it depends on whether or not they have installed an entirely different extension...?

**Comment by StephenWeatherford** [comment]
(Yes, I'm an extension author - https://github.com/microsoft/vscode-docker)

**Comment by StephenWeatherford** [comment]
@chrmarti Yes, and looking forward to that!
