### ISSUE TITLE
support reading from other stores

### ISSUE THREAD

**Issue by jfromaniello** [ukoloff/win-ca#16]
Can you add support for reading certificates from multiples stores?

I used to use a fork I did for your library where I implemented like this:
https://github.com/jfromaniello/win-ca/commit/f5a9fcd99fba90b4647b1f043c56fe970a971dd3#diff-9395dacd601c601e42e789fd2f69a6a6

but I see this is now implemented in c and I am not familiar with it.

I'd like to add certificates from `TRUSTEDPEOPLE` and `CA` in addition to `ROOT`. Example:

```js
winCa.each(['TRUSTEDPEOPLE', 'CA', 'ROOT'], function(ca){
//    if (moment(ca.validity.notAfter).isBefore()) { return; }
    cas.push( { pem: forge.pki.certificateToPem(ca) });
});
```

Thanks a lot!

**Comment by ukoloff** [comment]
Well, this is a challenging task for me. I take it.

**Comment by jfromaniello** [comment]
Thank you very much! You rock :)

**Comment by ukoloff** [comment]
Win-ca version 3.0.0 is about to appear. It passes all the tests and yes, it can fetch from any store. Keep waiting...

**Comment by ukoloff** [comment]
v3 is [published][npm]. New API call can read from any store, or from several stores at once:
```js
var ca = require('win-ca')
var list = [] // put certificates in DER format here
ca({
  store: ['root', 'ca'],
  ondata: list
})
```
[npm]: https://www.npmjs.com/package/win-ca

**Comment by jfromaniello** [comment]
Thank you very much! It works like a charm 💥
