### ISSUE TITLE
local certs distributed with release app

### ISSUE THREAD

**Issue by adammeyer** [ukoloff/win-ca#18]
I noticed when `npm run postinstall` is run, a copy of my local certs are copied to node_modules/win-ca/pem.  Which are then distributed with the released app.

Not a huge deal, just wondering if that is intentional or something that could be turned off.

**Comment by ukoloff** [comment]
You're right, this is legacy feature, preserved for compatibility (in fact it is simple test to see everything works as expected).

There is no simple way to turn it off, so *this is not a bug, but a feature* ;-)

Resulting `pem` folder should be deleted somehow - either manually or in `prepack` script of your package (or similar). I should note this in README...
