### ISSUE TITLE
package is causing npm install to fail on MSBUILD

### ISSUE THREAD

**Issue by mjiraboondilok** [ukoloff/win-ca#19]
I am running into an issue with this package in MSBUILD version 1.120.0 during `npm install`

npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! win-ca@3.0.5 postinstall: `node -e "try{require('.')}catch(e){}"`
npm ERR! Exit status 3221225477
npm ERR! 
npm ERR! Failed at the win-ca@3.0.5 postinstall script.

**Comment by mjiraboondilok** [comment]
Output from npm-cache logs:

179 verbose stack Error: win-ca@3.0.5 postinstall: `node -e "try{require('.')}catch(e){}"`
179 verbose stack Exit status 3221225477
179 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
179 verbose stack     at EventEmitter.emit (events.js:182:13)
179 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
179 verbose stack     at ChildProcess.emit (events.js:182:13)
179 verbose stack     at maybeClose (internal/child_process.js:962:16)
179 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
180 verbose pkgid win-ca@3.0.5
181 verbose cwd E:\Agent-1\_work\1\s\Composer\Composer\ComposerLaunchPad
182 verbose Windows_NT 10.0.14393
183 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
184 verbose node v10.12.0
185 verbose npm  v6.4.1
186 error code ELIFECYCLE
187 error errno 3221225477
188 error win-ca@3.0.5 postinstall: `node -e "try{require('.')}catch(e){}"`
188 error Exit status 3221225477
189 error Failed at the win-ca@3.0.5 postinstall script.
189 error This is probably not a problem with npm. There is likely additional logging output above.
190 verbose exit [ 3221225477, true ]

**Comment by ukoloff** [comment]
Yes, I can reproduce this error. It happens in Node v10.12.0.

I suggest this is a bug in Node.js. I tested in other versions (10.10.0, 10.11.0, 10.13.0, 10.14.2, 10.15.3) - they all works flawlessly.

I believe ugrading Node.js is the best solution. 10.12.0 is the latest non-LTS version in 10-th branch. 

I will investigate the issue, but I'm afraid nothing can be done with broken N-API...

**Comment by mjiraboondilok** [comment]
Upgraded node.js to 10.15.3 and this issue is resolved
