### ISSUE TITLE
Syntax Error in README example

### ISSUE THREAD

**Issue by ryanvgates** [ukoloff/win-ca#2]
It looks like the following code in the README example is

<pre>
for crt in ca.all()
  dst.write forge.pki.certificateToPem crt</pre>

should read
<pre>
for (crt in ca.all())
  dst.write forge.pki.certificateToPem crt</pre>

It causes a syntax error without the `()` around the inner part `crt in ca.all()`.

When I run it, I get the following error as well.

<pre>
for (crt in ca.all())
               ^

TypeError: ca.all is not a function
    at Object.<anonymous> (C:\Users\user\Source\Repos\testingNTLM\app.js:8:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
</pre>

Is there something that I'm missing?

**Comment by ukoloff** [comment]
First, I used CoffeeScript syntax in README. May be, it is somewhat outdated now. In JS it should be

```js
// Generated by CoffeeScript 2.3.0
var ca, crt, forge, i, len, ref;

ca = require('win-ca');
forge = require('node-forge');

ref = ca.all();
for (i = 0, len = ref.length; i < len; i++) {
  crt = ref[i];
  dst.write(forge.pki.certificateToPem(crt));
}
```
Or modern ES6's `for of`  may be used.

Second, `ca.all` missing may be caused by:

1) Running not under MS Windows (*Thanks, cap!*)

2) `win-ca` failed to properly install. It should install (on Windows) also `win-ca-ffi`, `ffi` and `node-forge`.

I don't have Windows machine so far, so I cannot test it just now. But I'll try it later.

I can remember, `ffi` is rather hard to properly install on fresh Windows machine. It requires Python and Microsoft Visual C++ to compile. This may be the case. Try issue `npm install --global windows-build-tools` command and wait. Then reinstall `win-ca`.

Or some package is possibly outdated. Try using older Node.js version. May be v6?

**Comment by ukoloff** [comment]
I found Windows machine, so the results are:

1) `ffi` failed to compile for Node v9. I'm afraid nothing can be done here.

2) `ffi` compiled for Node v8.9.4. So, Node v8 is the last version for `win-ca` to work so far.

3) `win-ca` seems to require administrative privileges (UAC to be disabled).

Everything can be fixed of course, but only if someone needs it.

**Comment by ryanvgates** [comment]
Thank you for clarifying that the example was in CoffeeScript. 

I am still getting the above error, `TypeError: ca.all is not a function`, when I try to do `ref = ca.all();`. I am running on Windows. I am using node v8.9.3. I successfully ran `npm install --global windows-build-tools`. I uninstalled using `npm uninstall --save win-ca`.

When I tried to re-install again, I got the following error.

<pre>
$ npm i --save win-ca

> ref@1.3.5 install C:\Users\user\Source\Repos\testingNTLM\node_modules\ref
> node-gyp rebuild


C:\Users\user\Source\Repos\testingNTLM\node_modules\ref>if not defined npm_config_node_gyp (node "C:\Users\user-CA\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\user-CA\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  binding.cc
  win_delay_load_hook.cc
..\src\binding.cc(643): warning C4996: 'Nan::ForceSet': was declared deprecated [C:\Users\user\Source\Repos\testingNTLM\node_modules\ref\build\binding.vcxproj]
  c:\users\user\source\repos\testingntlm\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of 'Nan::ForceSet'
..\src\binding.cc(644): warning C4996: 'Nan::ForceSet': was declared deprecated [C:\Users\user\Source\Repos\testingNTLM\node_modules\ref\build\binding.vcxproj]
  c:\users\user\source\repos\testingntlm\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of 'Nan::ForceSet'
     Creating library C:\Users\user\Source\Repos\testingNTLM\node_modules\ref\build\Release\binding.lib and object C:\Users\user\Source\Repos\testingNTLM\node_modules\ref\build\Release\binding.exp
  Generating code
  Finished generating code
  binding.vcxproj -> C:\Users\user\Source\Repos\testingNTLM\node_modules\ref\build\Release\\binding.node
  binding.vcxproj -> C:\Users\user\Source\Repos\testingNTLM\node_modules\ref\build\Release\binding.pdb (Full PDB)

> ffi@2.2.0 install C:\Users\user\Source\Repos\testingNTLM\node_modules\ffi
> node-gyp rebuild


C:\Users\user\Source\Repos\testingNTLM\node_modules\ffi>if not defined npm_config_node_gyp (node "C:\Users\user-CA\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\user-CA\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Building assembly file ..\..\..\deps\libffi\src\x86\win64.asm
  'ml64' is not recognized as an internal or external command,
  operable program or batch file.
C:\Users\user\Source\Repos\testingNTLM\node_modules\ffi\build\deps\libffi\ffi.targets(28,5): error MSB3721: The command "call ml64 "/nologo" "/c" "/FoRelease\obj\ffi\win64.obj" "..\..\..\deps\libffi\src\x86\win64.asm"" e
xited with code 1. [C:\Users\user\Source\Repos\testingNTLM\node_modules\ffi\build\deps\libffi\ffi.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\user-CA\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user-CA\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user\Source\Repos\testingNTLM\node_modules\ffi
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN testingntlm@1.0.0 No description
npm WARN testingntlm@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ffi@2.2.0 (node_modules\ffi):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ffi@2.2.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ win-ca@1.0.0
added 2 packages from 5 contributors and audited 1505 packages in 36.11s
found 0 vulnerabilities
</pre>

**Comment by ukoloff** [comment]
Yes, you have some strange problem with `ffi`.

Can you perform some more experiments?

1. Create new folder and run in it
```sh
npm init -y
npm i ffi
```
2. Do the same, but replace `ffi` with `ffi-napi`

3. Can you install 32-bit Node.js (still v8.*) and repeat steps 1 & 2?

So far, I suspect error is caused by 64-bit version of Node,js, but in AppVeyor such an error [doesn't happen](https://ci.appveyor.com/project/ukoloff/win-ca/build/1.0.61-newer/job/wfdoc59tfa8au722).

**Comment by ryanvgates** [comment]
When I did step 1, I got the following result.
<pre>$ npm i ffi --save

> ref@1.3.5 install C:\Users\user\Source\Repos\394444653\node_modules\ref
> node-gyp rebuild


C:\Users\user\Source\Repos\394444653\node_modules\ref>if not defined npm_config_node_gyp (node "C:\Users\user-CA\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\user-CA\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  binding.cc
  win_delay_load_hook.cc
..\src\binding.cc(643): warning C4996: 'Nan::ForceSet': was declared deprecated [C:\Users\user\Source\Repos\394444653\node_modules\ref\build\binding.vcxproj]
  c:\users\user\source\repos\394444653\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of 'Nan::ForceSet'
..\src\binding.cc(644): warning C4996: 'Nan::ForceSet': was declared deprecated [C:\Users\user\Source\Repos\394444653\node_modules\ref\build\binding.vcxproj]
  c:\users\user\source\repos\394444653\node_modules\nan\nan_maybe_43_inl.h(130): note: see declaration of 'Nan::ForceSet'
     Creating library C:\Users\user\Source\Repos\394444653\node_modules\ref\build\Release\binding.lib and object C:\Users\user\Source\Repos\394444653\node_modules\ref\build\Release\binding.exp
  Generating code
  Finished generating code
  binding.vcxproj -> C:\Users\user\Source\Repos\394444653\node_modules\ref\build\Release\\binding.node
  binding.vcxproj -> C:\Users\user\Source\Repos\394444653\node_modules\ref\build\Release\binding.pdb (Full PDB)

> ffi@2.2.0 install C:\Users\user\Source\Repos\394444653\node_modules\ffi
> node-gyp rebuild


C:\Users\user\Source\Repos\394444653\node_modules\ffi>if not defined npm_config_node_gyp (node "C:\Users\user-CA\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\user-CA\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Building assembly file ..\..\..\deps\libffi\src\x86\win64.asm
  'ml64' is not recognized as an internal or external command,
  operable program or batch file.
C:\Users\user\Source\Repos\394444653\node_modules\ffi\build\deps\libffi\ffi.targets(28,5): error MSB3721: The command "call ml64 "/nologo" "/c" "/FoRelease\obj\ffi\win64.obj" "..\..\..\deps\libffi\src\x86\win64.asm"" exited with code
 1. [C:\Users\user\Source\Repos\394444653\node_modules\ffi\build\deps\libffi\ffi.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\user-CA\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user-CA\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user\Source\Repos\394444653\node_modules\ffi
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN 394444653@1.0.0 No description
npm WARN 394444653@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user-CA\AppData\Roaming\npm-cache\_logs\2018-06-04T19_03_46_957Z-debug.log
</pre>

When I did step 2, I got the following

<pre>$ npm i --save ffi-napi

> ref-napi@1.4.0 install C:\Users\user\Source\Repos\394444653.1\node_modules\ref-napi
> node-gyp rebuild


C:\Users\user\Source\Repos\394444653.1\node_modules\ref-napi>if not defined npm_config_node_gyp (node "C:\Users\user-CA\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\user-CA\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  win_delay_load_hook.cc
  Generating code
  Finished generating code
  nothing.vcxproj -> C:\Users\user\Source\Repos\394444653.1\node_modules\ref-napi\build\Release\\nothing.node
  nothing.vcxproj -> C:\Users\user\Source\Repos\394444653.1\node_modules\ref-napi\build\Release\nothing.pdb (Full PDB)
  binding.cc
  win_delay_load_hook.cc
..\src\binding.cc(229): warning C4244: 'argument': conversion from 'int64_t' to 'double', possible loss of data [C:\Users\user\Source\Repos\394444653.1\node_modules\ref-napi\build\binding.vcxproj]
..\src\binding.cc(298): warning C4244: 'argument': conversion from 'uint64_t' to 'double', possible loss of data [C:\Users\user\Source\Repos\394444653.1\node_modules\ref-napi\build\binding.vcxproj]
     Creating library C:\Users\user\Source\Repos\394444653.1\node_modules\ref-napi\build\Release\binding.lib and object C:\Users\user\Source\Repos\394444653.1\node_modules\ref-napi\build\Release\binding.exp
  Generating code
  Finished generating code
  binding.vcxproj -> C:\Users\user\Source\Repos\394444653.1\node_modules\ref-napi\build\Release\\binding.node
  binding.vcxproj -> C:\Users\user\Source\Repos\394444653.1\node_modules\ref-napi\build\Release\binding.pdb (Full PDB)

> ffi-napi@2.4.3 install C:\Users\user\Source\Repos\394444653.1\node_modules\ffi-napi
> node-gyp rebuild


C:\Users\user\Source\Repos\394444653.1\node_modules\ffi-napi>if not defined npm_config_node_gyp (node "C:\Users\user-CA\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\user-CA\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Building assembly file ..\..\..\deps\libffi\src\x86\win64.asm
  'ml64' is not recognized as an internal or external command,
  operable program or batch file.
C:\Users\user\Source\Repos\394444653.1\node_modules\ffi-napi\build\deps\libffi\ffi.targets(28,5): error MSB3721: The command "call ml64 "/nologo" "/c" "/FoRelease\obj\ffi\win64.obj" "..\..\..\deps\libffi\src\x86\win64.asm"" exited wi
th code 1. [C:\Users\user\Source\Repos\394444653.1\node_modules\ffi-napi\build\deps\libffi\ffi.vcxproj]
  win_delay_load_hook.cc
  Generating code
  Finished generating code
  nothing.vcxproj -> C:\Users\user\Source\Repos\394444653.1\node_modules\ffi-napi\build\Release\\nothing.node
  nothing.vcxproj -> C:\Users\user\Source\Repos\394444653.1\node_modules\ffi-napi\build\Release\nothing.pdb (Full PDB)
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\user-CA\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user-CA\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user\Source\Repos\394444653.1\node_modules\ffi-napi
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN 394444653.1@1.0.0 No description
npm WARN 394444653.1@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi-napi@2.4.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi-napi@2.4.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user-CA\AppData\Roaming\npm-cache\_logs\2018-06-04T19_07_01_580Z-debug.log
</pre>

I'll install 32-bit Node.js and share the results in the next comment.

**Comment by ukoloff** [comment]
Windows build tools are definitely broken. Unfortunately, I'm not an expert in it.

Do you have some version of Visual Studio installed?

Is there folder `C:\Program Files\Microsoft Visual Studio 14.0\VC\bin` on your computer? Or something like that (Program Files x86, another version of VS, etc)?

**Comment by ryanvgates** [comment]
I do have Visual Studio installed. I have it installed in `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin` though instead of `C:\Program Files\Microsoft Visual Studio 14.0\VC\bin`. Should I open an issue with [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools)?

**Comment by ukoloff** [comment]
Yeah, there should be a lot more expertise on the topic there. So you should try.

By the way, they say, one should install .Net 4.5.1 onto Win7. Do you have one?

As for me, I'm planning to build precompiled version of `ffi-napi` for Win32 (and 64 of course) to resolve this issue for ever. [edge](https://github.com/tjanczuk/edge) does this, maye be I can do the same.

**Comment by ryanvgates** [comment]
I do have .NET 4.5.1 installed. I am using Windows 10.
![image](https://user-images.githubusercontent.com/1400394/41050646-02e2f248-6982-11e8-9146-65dc65461565.png)

**Comment by ryanvgates** [comment]
I added `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin` to my path and it seemed to fix the error with installing the package. I'm going to try to run the code again.

**Comment by ryanvgates** [comment]
That did the trick! Thank you for all your help troubleshooting this.

**Comment by ukoloff** [comment]
Can you do some testing for me?

New version of `win-ca` requires no compilation at all. Install with `npm install win-ca@n-api`.

Please, test it at your environment.

**Comment by ryanvgates** [comment]
It worked for me locally and on one dev server, but not on the other. On the one that didn't work, I get the error.
<pre>
2391 info teardown Done in 0.003s
2392 verbose stack Error: win-ca@2.0.0-rc1 postinstall: `node -e "try{require('.')}catch(e){}"`
2392 verbose stack Exit status 3221225477
2392 verbose stack     at EventEmitter.<anonymous> (C:\Users\RyanGat\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
2392 verbose stack     at emitTwo (events.js:106:13)
2392 verbose stack     at EventEmitter.emit (events.js:191:7)
2392 verbose stack     at ChildProcess.<anonymous> (C:\Users\RyanGat\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
2392 verbose stack     at emitTwo (events.js:106:13)
2392 verbose stack     at ChildProcess.emit (events.js:191:7)
2392 verbose stack     at maybeClose (internal/child_process.js:891:16)
2392 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
2392 verbose stack From previous event:
2392 verbose stack     at Installer.runScript (C:\Users\RyanGat\AppData\Roaming\npm\node_modules\npm\node_modules\libcipm\index.js:353:17)
2392 verbose stack     at runScript.then.then.then.then (C:\Users\RyanGat\AppData\Roaming\npm\node_modules\npm\node_modules\libcipm\index.js:290:26)
2392 verbose stack From previous event:
2392 verbose stack     at tree.forEachAsync (C:\Users\RyanGat\AppData\Roaming\npm\node_modules\npm\node_modules\libcipm\index.js:290:10)
2392 verbose stack     at P.resolve.then (C:\Users\RyanGat\AppData\Roaming\npm\node_modules\npm\node_modules\libcipm\node_modules\npm-logical-tree\index.js:75:14)
2392 verbose stack From previous event:
2392 verbose stack     at LogicalTree.forEachAsync (C:\Users\RyanGat\AppData\Roaming\npm\node_modules\npm\node_modules\libcipm\node_modules\npm-logical-tree\index.js:74:33)
2392 verbose stack     at dep (C:\Users\RyanGat\AppData\Roaming\npm\node_modules\npm\node_modules\libcipm\node_modules\npm-logical-tree\index.js:78:22)
2392 verbose stack From previous event:
2392 verbose stack     at promiseMap (C:\Users\RyanGat\AppData\Roaming\npm\node_modules\npm\node_modules\libcipm\node_modules\npm-logical-tree\index.js:180:14)
2392 verbose stack     at fn (C:\Users\RyanGat\AppData\Roaming\npm\node_modules\npm\node_modules\libcipm\node_modules\npm-logical-tree\index.js:76:16)
2392 verbose stack From previous event:
2392 verbose stack     at tree.forEachAsync (C:\Users\RyanGat\AppData\Roaming\npm\node_modules\npm\node_modules\libcipm\index.js:264:10)
2392 verbose stack     at P.resolve.then (C:\Users\RyanGat\AppData\Roaming\npm\node_modules\npm\node_modules\libcipm\node_modules\npm-logical-tree\index.js:75:14)
2392 verbose stack     at runCallback (timers.js:672:20)
2392 verbose stack     at tryOnImmediate (timers.js:645:5)
2392 verbose stack     at processImmediate [as _immediateCallback] (timers.js:617:5)
2392 verbose stack From previous event:
2392 verbose stack     at LogicalTree.forEachAsync (C:\Users\RyanGat\AppData\Roaming\npm\node_modules\npm\node_modules\libcipm\node_modules\npm-logical-tree\index.js:74:33)
2392 verbose stack     at Installer.buildTree (C:\Users\RyanGat\AppData\Roaming\npm\node_modules\npm\node_modules\libcipm\index.js:257:17)
2392 verbose stack     at Installer.timedStage (C:\Users\RyanGat\AppData\Roaming\npm\node_modules\npm\node_modules\libcipm\index.js:43:34)
2392 verbose stack     at timedStage.then.then.then.pkgJsons (C:\Users\RyanGat\AppData\Roaming\npm\node_modules\npm\node_modules\libcipm\index.js:54:30)
2392 verbose stack From previous event:
2392 verbose stack     at Installer.run (C:\Users\RyanGat\AppData\Roaming\npm\node_modules\npm\node_modules\libcipm\index.js:54:8)
2392 verbose stack     at EventEmitter.ci (C:\Users\RyanGat\AppData\Roaming\npm\node_modules\npm\lib\ci.js:30:6)
2392 verbose stack     at Object.commandCache.(anonymous function) (C:\Users\RyanGat\AppData\Roaming\npm\node_modules\npm\lib\npm.js:159:13)
2392 verbose stack     at EventEmitter.<anonymous> (C:\Users\RyanGat\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:123:30)
2392 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:73:7)
2392 verbose stack     at process._tickCallback (internal/process/next_tick.js:104:9)
</pre>

**Comment by ukoloff** [comment]
Well, error message are quite meaningless.

I suspect Node.js version. What do you use there? Run
```
node -v
npm -v
```
New version of `win-ca` should fail at Node v4, 5 and 7. But not in this way...

**Comment by ryanvgates** [comment]
one server
node -v => v8.9.4
npm -v => 6.1.0

second server
node -v => v6.11.0
npm -v => 6.1.0

local
node -v => 8.11.2
npm -v => 6.1.0

**Comment by ukoloff** [comment]
Yes, it is a matter of Node version. N-API is supported from v6.14.2, you have 6.11.0

You may upgrade your Node or wait and do nothing. Final version of `win-ca` is supposed to handle the issue.

**Comment by ryanvgates** [comment]
Do you have a timeline for the Final version of `win-ca`?

**Comment by ukoloff** [comment]
I hope, it will become available this week, but not for sure. I play with it in my spare time.

**Comment by ukoloff** [comment]
Okay, try `win-ca@both`. If it succeed, it will be released as v2.

**Comment by ukoloff** [comment]
`win-ca` v2.0 released. Should work everywhere without compilation.
