### ISSUE TITLE
Open Certificate import wizard ?

### ISSUE THREAD

**Issue by Sangdt** [ukoloff/win-ca#20]
Can this library open the Certificate import wizard on windows or mac ?.

I'm currently working on a small application that do digital signing with pfx and other type of key store in client local Certificate. I intend to use nodejs as native application at client side to get and import their cert. Everything when great except the import certs part. 

I can easily do this with c#, does this library  support that ? I didn't see any api that allow me to do so.
I'm sorry if this not an issue.

**Comment by ukoloff** [comment]
This is clearly beyond of scope of the package.

As far as I know, the best way of importing ceritificates on Windows is PowerShell. One can run it with [child_process] or even run in-process with [edge-js]. I believe [edge-js] can run `C#` code directly:

```js
var edge = require('edge-js');
 
var helloWorld = edge.func(`
    async (input) => { 
        return ".NET Welcomes " + input.ToString(); 
    }
`);
```

[child_process]: https://nodejs.org/api/child_process.html
[edge-js]: https://www.npmjs.com/package/edge-js
