### ISSUE TITLE
Not work with asar

### ISSUE THREAD

**Issue by hfutxqd** [ukoloff/win-ca#22]

**Comment by ukoloff** [comment]
You are very laconic. Is this SPARTA?!!

**Comment by hfutxqd** [comment]
I'm sorry for the  laconic description. I use win-ca in my electron application, and it works well. However, when I pack the code  with electron-builder into an exe file, and run the exe file, it will get an error dialog about ChildProcess.

**Comment by ukoloff** [comment]
Well, can you make some testing? 

Download [fallback.js.zip], unpack, replace `win-ca/lib/fallback.js`, build exe-file and run it.

[fallback.js.zip]: /ukoloff/electron-win-ca/files/3216184/fallback.js.zip

**Comment by hfutxqd** [comment]
OK. It works.

**Comment by ukoloff** [comment]
`win-ca` v3.1.0 is out. Should fix your problem.
