### ISSUE TITLE
Support help needed for Dart port

### ISSUE THREAD

**Issue by certaintls** [ukoloff/win-ca#25]
I am working on a Dart port of this library, I have a few questions below, if you can spare a few minutes, it would be much appreciated:

> win-ca/fallback does the same, but it never uses N-API for fetching certificates, so it should work in all versions of Node.js as well as inside Electron application.

Sounds like `win-ca` uses `crypt32.dll` while `win-ca/fallback` doesn't. How does `win-ca/fallback` get access to the cert list? https://github.com/ukoloff/win-ca/blob/master/fallback/index.js look empty

**Comment by ukoloff** [comment]
> Sounds like `win-ca` uses `crypt32.dll` while `win-ca/fallback` doesn't. How does `win-ca/fallback` get access to the cert list?

Exactly. When `crypt32.dll` is impossible to use, a special binary utility is launched, that just enumerates certificates and dumps them in base64 format. Source code of that utility is is  https://github.com/ukoloff/win-ca/blob/master/n-api/roots.c and it is launched and parsed by https://github.com/ukoloff/win-ca/blob/master/src/fallback.ls Hope this helps.

>  https://github.com/ukoloff/win-ca/blob/master/fallback/index.js look empty

This file (along with `api` folder) is just quick-n-dirty hack to provide different entry points. Main entry point <https://github.com/ukoloff/win-ca/blob/master/src/index.ls> requires this file, checks whether it was already required and switches to appropriate mode. You can do it in not such a magical way ;-)

**Comment by certaintls** [comment]
Thanks a lot for the information. On the other hand, have you considered get the output from 'certutil -store root' ?

**Comment by ukoloff** [comment]
Parcing `certutil` output would be much harder task.
