### ISSUE TITLE
"Saved [date] by win-ca" in every certificate can break building process

### ISSUE THREAD

**Issue by travenec** [ukoloff/win-ca#26]
Hello,

when `win-ca` is used in environment where _bundle/asar/any other build_ result files are checked by checksum, a comment in every PEM mentioning save date affects the hash.

Imagine situation: The same code being built twice in CI. Since CI does builds from scratch, it starts by modules installation and therefor every build gets different certificate files. The difference is of course in the saved date.

```
Subject	US/Washington/Redmond/Microsoft Corporation/Microsoft ECC TS Root Certificate Authority 2018
Valid	180227205134Z - 430227210012Z
Saved	2020-04-03 16:37:58 GMT+0000 by win-ca@3.1.1
-----BEGIN CERTIFICATE-----
```

This breaks the checksum of the files and other mechanisms following.

We managed by adjusting the files our own way. This is just to consider whether the comment is really necessary.

Greetings.

**Comment by ukoloff** [comment]
Well, I  got the idea. Not sure how to fix it, though.

It seems to me, the date of saving is not very important information. May be we should just omit it. Let me think a bit...

**Comment by ukoloff** [comment]
win-ca@3.2.0 is published. Date is omitted in the saved certificates.

Please, test.
