### ISSUE TITLE
can this library be used in browser context?

### ISSUE THREAD

**Issue by sumantfordev** [ukoloff/win-ca#27]
i am trying to see if pulling the certificates is possible when bundled up wit angular/typescript from a browser, then it can fetch certs from the user device certificate store.

**Comment by ukoloff** [comment]
No, this library will *not* work in browser, it works only in standalone Windows applications.

But I also believe that there is no way to enumerate root certificates from browser. Should be blocked as security breach.

**Comment by sumantfordev** [comment]
Thanks for the clarification.
