### ISSUE TITLE
How to identify certificates

### ISSUE THREAD

**Issue by ryanvgates** [ukoloff/win-ca#3]
How can I identify the certificate that I intend to use?

I have all of the certificates that are installed on my machine. What's the correct way to filter out the one that I need from the list?

<pre>
var crt, i, len, ref = ca.all();

for (i = 0, len = ref.length; i < len; i++){
    crt = ref[i];
    console.log("cert index " + i + " cert serial number" + crt.serialNumber + " subject " + crt.subject.attributes[0].value);
}
</pre>

I tried to use serialNumber and subject. Serial Number (e.g. `355d700b594f0f8548854398397ad5d9`) doesn't match what I see in the mmc.exe console under Certificates (e.g. `‎50 4f 34 9c 00 01 99 02 54 a9`). 

Subject can be duplicated so I hesitate to use that.

**Comment by ryanvgates** [comment]
Thank you for asking that question! I don't need to be filtering. I misunderstood the purpose of win-ca and assumed it was loading all of the certs rather than just the root certificates. I did have to map from what win-ca produces to pem cert format with the following code.

<pre>
var express = require('express'),
    ntlm = require('express-ntlm'),
    ca = require('win-ca'),
    forge = require('node-forge');
var app = express();

var ref = ca.all();

app.use("/auth/*", ntlm({
    debug: function() {
        var args = Array.prototype.slice.apply(arguments);
        console.log.apply(null, args);
    },
    domain: 'myDomain',
    domaincontroller: ['ldaps://my.domain', null],
    tlsOptions: {
        //trusted certificate authorities (can be extracted from the server with openssh)
        ca: ref.map(function(cert) { return forge.pki.certificateToPem(cert); }),
    }
}));
</pre>

**Comment by ukoloff** [comment]
Furthermore, try `tlsOptions: {ca: https.globalAgent.options.ca}`, it should contain the same list.

**Comment by ukoloff** [comment]
As far as I know, Node.js doesn't support `import` yet. Use `https = require 'https'` or even `tlsOptions: {ca: require('https').globalAgent.options.ca}`

**Comment by ryanvgates** [comment]
In the application, it was using babel to transpile ES6 to ES5. Sorry for the confusion on import vs require.
