### ISSUE TITLE
Allow roots.exe's path to be configurable

### ISSUE THREAD

**Issue by vmsp** [ukoloff/win-ca#35]
The path to `roots.exe` is currently set as a constant: https://github.com/ukoloff/win-ca/blob/master/src/fallback.ls#L5

In less vanilla packaging scenarios, it's useful to let the user configure where this executable will be. [Like when using pkg](https://github.com/vercel/pkg/issues/1002). This path could be passed to the initialization function. E.g.

``` javascript
var ca = require('win-ca/api');
ca({fallback: true, inject: true, roots: path.join(...)});
```

See also this note on [node-regedit](https://github.com/ironSource/node-regedit#a-note-about-electron) for an example of this feature.

**Comment by ukoloff** [comment]
Well, it's reasonable, I'm going to implement.

**Comment by ukoloff** [comment]
v3.4.5 is published. New function `.exe()` added. eg
```js
var ca = require('win-ca/api')

ca.exe('/full/path/to/roots.exe')
ca({fallback: true, inject: true})
```
Feel free to test.

**Comment by vmsp** [comment]
It's working as expected. Thank you.
