### ISSUE TITLE
Permissions Required To Work

### ISSUE THREAD

**Issue by ryanvgates** [ukoloff/win-ca#4]
What permissions are required to use this package to help configure LDAPS in [express-ntlm](https://github.com/einfallstoll/express-ntlm)?

I have a site that works as long as the Application Pool runs under a Local Administrator on that machine. I'd like to limit the service account's permission that the Application Pool runs under for better security. I have granted 
1. Grant read/execute to nodejs folder 
`icacls "C:\program files\nodejs" /grant domain\svc_account:(OI)(CI)rx`
2. Grant read/execute to iinode folder 
`icacls "C:\program files\iisnode" /grant domain\svc_account:(OI)(CI)rx`
3. Grant Full Control to the website folder
`icacls "D:\Websites\is-logging-api" /grant domain\svc_account:(OI)(CI)F`
4. Full Control to the private key used by the certificate (Open Certificates -> Right Click on yours -> All Tasks -> Manage Private Keys)

Please let me know if you need additional information.

**Comment by ukoloff** [comment]
To the best of my knowledge, no permissions are required to fetch root certificates. They are visible to all locally logged users.

Then `win-ca` attempts to save fetched certificates inside `node_mode` modules folder, which can fail for arbitrary user, but this folder should be owned by the user that runs applications. 

So, no additional permissions are to be required.

**Comment by rdebath** [comment]
As I'm not using Nodejs on this machine, just vscode, so this looks like the reason the extension appears to be doing nothing.

I'm running as a standard user on Windows 10, what permissions to which locations do I have to give for this to work correctly.

**Comment by ukoloff** [comment]
First, go to `%USERPROFILE%\.vscode\extensions\ukoloff.win-ca-n.n.n\node_modules\win-ca\` folder. Check whether you can create its subfolders manually. If you can, permissions are likely to be not an issue.

Second, close VSCode (if any) and start it again. Immediately go to Help / Toggle Developer Tools, then select `Console` on the top. Look for error messages concerning `win-ca`.
