### ISSUE TITLE
Extension breaks VSCode https connections when installed on MacOS

### ISSUE THREAD

**Issue by RomanKornev** [ukoloff/win-ca#40]
I have settings sync turned on, so this extension got enabled on my Mac as well. As a result, any extension that makes an `https://` request just doesn't work with errors such as `Unable to get local issuer certificate`, etc. Is there a way to only run it on Windows?

**Comment by ukoloff** [comment]
It's rather strange, since `win-ca` checks whether it runs on Windows (`process.platform == 'win32'`) and if not - does nothing.

And it worked okay earlier.

Unfortunately, I cannot test it on Mac. I will try to debug it on Linux though...

**Comment by ukoloff** [comment]
I believe I found the error. Can you check?

[VSIX][win-ca-3.4.5.vsix.zip] file is attached. Unzip and install (`F1` Extensions: Install from VSIX...). It should correctly work everywhere.


[win-ca-3.4.5.vsix.zip]: https://github.com/ukoloff/win-ca/files/7130754/win-ca-3.4.5.vsix.zip

**Comment by RomanKornev** [comment]
Yeah, issue seems to be resolved in this update

**Comment by ukoloff** [comment]
Published v3.4.5
