### ISSUE TITLE
Intellij extension

### ISSUE THREAD

**Issue by RafaelGB** [ukoloff/win-ca#47]
Hi! First of all thanks for your fantastic work. I was trying to reproduce the win-ca behavior under Intellij too. With VSCODE works like a charm.

Could it be possible to take advantage of this implementation under a plugin in intellij Idea?

**Comment by ukoloff** [comment]
I know nothing about Intellij guts, but I think, its plugins should be in Java (or maybe Kotlin / Scala), so my code cannot be directly used there. 

As a quick-n-dirty fix, one can run `roots.exe`, store its output to some folder and set some environment variables (`SSL_CERT_DIR` or its Java equivalent). But you still need someone, who knows how to write Inellij plugins.
