### ISSUE TITLE
I wrote a similar module for MacOS

### ISSUE THREAD

**Issue by jfromaniello** [ukoloff/win-ca#5]
Hi! I just wanted to let you know that I have created a similar module for Mac OS. I tried to maintain compatibility with win-ca so it gets easier to build applications using both.

https://github.com/jfromaniello/mac-ca

(It is still needs more testing though.)

**Comment by ukoloff** [comment]
Okay, I noted your module in README.

**Comment by jfromaniello** [comment]
Thank you!
