### ISSUE TITLE
Rebuild for Electron 3.0.x

### ISSUE THREAD

**Issue by chs09** [ukoloff/win-ca#8]
### Win-Ca 2.1.0 will not start up with Electron 3.x
With Electron version 3.x initializing crypt32-{arch}.node will fail. Rebuilding with [Electron-Rebuild](https://www.npmjs.com/package/electron-rebuild) fixes this. Please release a new version of win-ca which is compatible with Electron 3.x.

**Comment by chs09** [comment]
Ah ok - I was not aware of that either since I just started with Electron development. Electron seems to use a different Node.js Version. As I understand the docs, the module has to be built with the never Node.js Version. This can be done with [electron-rebuild](https://github.com/electron/electron-rebuild). I am not sure whether the modules have to be rebuilt with electron-rebuild or if it is sufficient to compile them with a newer node.js version.

I only tested electron-rebuild. The newly compiled modules work together with electron 2.x AND 3.x.
Electron 3 uses Node v10 / Electron 2 uses Node v8.

**Comment by ukoloff** [comment]
And if I recompile module for Electron, will it stop working for regular Node?

**Comment by chs09** [comment]
Ok, I have tested that. The recompiled files do not work with regular Node :( do we need an electron branch? Do you have any idea?

**Comment by ukoloff** [comment]
I believe we should test whether we running under Electron, then loading its DLL or fallback to roots.exe

But I have no idea how to detect this. Electron should provide this, I hope.

**Comment by chs09** [comment]
Okay, it seems that there is no easy solution. The Problem is known: [N-api builds not cross runtime on windows](https://github.com/nodejs/node-addon-api/issues/269). So providing different binaries for electron and regular node would probably the best solution.

Testing whether the module is running under Electron seems to be simple [npm.js/is-electron](https://www.npmjs.com/package/is-electron).

**Comment by ukoloff** [comment]
> Testing whether the module is running under Electron seems to be simple npm.js/is-electron.
Really simple. I'm going to create new version of `win-ca` with this test incorporated. May be tomorrow or in a few days...

**Comment by ukoloff** [comment]
I've justt published v2.1.0-electron.

Please. test it.
```sh
npm i win-ca@2.1.0-electron
```

**Comment by chs09** [comment]
Hey, thank you for your help.

I think there is an error in index.js - the coffee script compiles to
```
this.each = electron || (this.nApi = !!process.versions.napi) ? require('./each') : require('./each.fallback');
```
but I think it should be
```
this.each = !electron && (this.nApi = !!process.versions.napi) ? require('./each') : require('./each.fallback');
```
So the fallback will be used if it is electron or NAPI Version does not match. When I change this it's working with the fallback.

**Comment by chs09** [comment]
One additional thought: wouldn't it be better to use the fallback version automatically in case of an error?

```javascript
try {
  this.each =  require('./each');
} catch (e) {
  this.each = require('./each.fallback');
}
```

**Comment by ukoloff** [comment]
> One additional thought: wouldn't it be better to use the fallback version automatically in case of an error?

No, this was my first idea, but id didn't work. When DLL fails to load, whole Node.js remains in unstable state. So, I had to detect N-Api availability.

> I think there is an error in index.js 

It seems to me, you are right! 

As quick fix you can patch it in place, after installation - in order to test.

And of course, I'll make fixed version - soon.

**Comment by ukoloff** [comment]
Version `2.1.1-electron` is out there.

**Comment by chs09** [comment]
Hey, it finally works. When Electron is active win-ca uses the fallback. :thumbsup:
